{
 "title": "E-commerce API - Observabilidad",
 "tags": [
  "devops",
  "fastapi",
  "ecommerce"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Estado de la API",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi-ecommerce\"}",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Tasa de solicitudes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fastapi-ecommerce\"}[1m]))",
     "legendFormat": "Solicitudes/s"
    }
   ]
  },
  {
   "title": "Errores del servidor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fastapi-ecommerce\",status=~\"5..\"}[5m]))",
     "legendFormat": "Errores 5xx/s"
    }
   ]
  },
  {
   "title": "Latencia p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_highr_seconds_bucket{job=\"fastapi-ecommerce\"}[5m])) by (le))",
     "legendFormat": "Latencia p95"
    }
   ]
  },
  {
   "title": "Consumo de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi-ecommerce\"}[5m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Consumo de memoria",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastapi-ecommerce\"}",
     "legendFormat": "Memoria residente"
    }
   ]
  }
 ]
}